### ISSUE TITLE
the code doesn't seem to support stride in convolution steps

### ISSUE THREAD

**Issue by Pagey** [Bartzi/visual-backprop-mxnet#1]
hey- thanks dearly for the code- i added support for stride in convolution steps (e.g. as in alexnet or resnet) 
it seems to work, but there seem to be grid artifacts created due to the stride in the deconvolution- any idea why this is happening but doesn't seem to appear in the original paper?

`import json

import mxnet as mx

def string_to_tuple(string):
    return string.strip('(').strip(')').split(',')

def combine_feature_maps(intermediate_symbols, node, nodes, scaled_feature):
    data_input_node = nodes[node['inputs'][0][0]]
    try:
        data_input_symbol = intermediate_symbols["{}_output".format(data_input_node['name'])]
    except ValueError:
        try:
            data_input_symbol = intermediate_symbols[data_input_node['name']]
        except ValueError:
            data_input_symbol = intermediate_symbols["{}_output0".format(data_input_node['name'])] # MY looks like lrn has output0

    averaged_feature_map = mx.symbol.mean(data_input_symbol, axis=1, keepdims=True)

    fixed_scaled_feature = mx.symbol.Crop(scaled_feature, averaged_feature_map) # MY making sure they're same size- in case it was adjusted due to stride not matching pad, size etc

    feature_map = fixed_scaled_feature * averaged_feature_map
    return feature_map

def build_visual_backprop_symbol(start_symbol, input_name=None):
    computational_graph = json.loads(start_symbol.tojson())
    nodes = computational_graph['nodes']

    assert nodes[-1]['op'] == 'Activation', 'Visual Backprop needs an activation node as starting point!'

    intermediate_symbols = start_symbol.get_internals()

    feature_map = mx.symbol.mean(start_symbol, axis=1, keepdims=True)
    for node in reversed(nodes):
        if input_name is not None and node['name'] == input_name or node['name'] == 'data':
            break

        node_attrs = node.get('attrs', None)
        if node['op'] == 'Convolution':
            kernel_height, kernel_width = map(int, string_to_tuple(node_attrs['kernel']))
            stride_height, stride_width = map(int, string_to_tuple(node_attrs.get('stride', '(1, 1)')))# MY added for stride in convolution
            pad_height, pad_width = map(int, string_to_tuple(node_attrs.get('pad', '(0, 0)')))
            scaled_feature = mx.symbol.Deconvolution(
                data=feature_map,
                weight=mx.symbol.ones((1, 1, kernel_height, kernel_width)),
                kernel=(kernel_height, kernel_width),
                stride=(stride_height, stride_width), # MY added this- was missing???
                pad=(pad_height, pad_width),
                num_filter=1,
                adj=(stride_height - 1, stride_width - 1) # MY added this for rounding in case of stride not matching size (+/-1) will be cropped anyway before mul - will take care of it with Crop if needed in combine_feature_maps
            )
            #scaled_feature=mx.symbol.pad(scaled_feature, mode='edge', pad_width=(0, 0, 0, 0, 0, stride_height, 0, stride_width)) # MY adding edge padding anyway and will crop if too big- this is for for rounding in case of stride not matching size (+/-1)

            feature_map = combine_feature_maps(intermediate_symbols, node, nodes, scaled_feature)
        elif node['op'] == 'Pooling':
            kernel_height, kernel_width = map(int, string_to_tuple(node_attrs['kernel']))
            #stride_height, stride_width = map(int, string_to_tuple(node_attrs['stride']))
            stride_height, stride_width = map(int, string_to_tuple(node_attrs.get('stride', '(1, 1)')))  # MY need default- theoretically could be pooling without stride..
            scaled_feature = mx.symbol.Deconvolution(
                data=feature_map,
                weight=mx.symbol.ones((1, 1, kernel_height, kernel_width)),
                kernel=(kernel_height, kernel_width),
                stride=(stride_height, stride_width),
                num_filter=1,
                adj=(stride_height - 1, stride_width - 1) # this is sometimes needed- will take care of it with Crop if needed in combine_feature_maps
            )

            feature_map = combine_feature_maps(intermediate_symbols, node, nodes, scaled_feature)
        else:
            continue

    # normalize feature map
    min_value = mx.symbol.min(feature_map)
    max_value = mx.symbol.max(feature_map)
    feature_map = mx.symbol.broadcast_sub(feature_map, min_value)
    feature_map = mx.symbol.broadcast_mul(feature_map, 1.0 / (max_value - min_value))
    return feature_map
`

**Comment by Bartzi** [comment]
fixed with #2
